### ISSUE TITLE
What do you use this for?

### ISSUE THREAD

**Issue by JesseTG** [Razenpok/Razensoft.Mapper#1]
Hi there. I saw this library and I intuitively believe that it could be useful in my project, but I couldn't tell you how exactly. I don't believe games usually interact with databases directly, so I can't see how the use cases [described in the article you linked in the README](https://rehansaeed.com/a-simple-and-fast-object-mapper/#why-use-an-object-mapper) are directly applicable.

Yet you took the time to slice parts of Dotnet-Boxed into Unity packages and tweak them in Unity-specific ways, so I assume you found *some* interesting client-side use case. Would you mind sharing more about what you're using `Razensoft.Mapper` for? Thank you!

**Comment by razenpok** [comment]
I tend to separate serialization models from game logic models, hence there is some amount of code dedicated to serialization mapping:

- When writing/reading save files
- When working with network - serializing server request/responses
- Even when working with actual databases - using SQLite or LiteDB in games is not that uncommon

I also practice Clean Architecture approach by Uncle Bob, which uses requests/responses between application layers which also requires mapping.

Hope this helps!
